define(function() {
	return {
		"Author": "allenAugustine",
		"Email": "iallenaugustine@gmail.com",
		"case": [{
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/1.jpg",
			"sourceimg": "images/1.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/2.jpg",
			"sourceimg": "images/2.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/3.jpg",
			"sourceimg": "images/3.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/4.jpg",
			"sourceimg": "images/4.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/5.jpg",
			"sourceimg": "images/5.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/6.jpg",
			"sourceimg": "images/6.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/7.jpg",
			"sourceimg": "images/7.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/8.jpg",
			"sourceimg": "images/8.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/2.jpg",
			"sourceimg": "images/2.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/3.jpg",
			"sourceimg": "images/3.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/4.jpg",
			"sourceimg": "images/4.jpg"
		}, {
			"name": "少林塔沟教育集团",
			"description": "少林塔沟教育集团始创于1978年，是由出身于武术世家的全国著名拳师、中国民间文化杰出传承人、国家武术九段",
			"thumbnail": "images/5.jpg",
			"sourceimg": "images/5.jpg"
		}]
	};
});