define(function() {
  return {
    "Author": "allenAugustine",
    "Email": "iallenaugustine@gmail.com",
    "case": [{
      "name": "相豫网",
      "description": "您身边的婚恋专家!",
      "thumbnail": "images/3.jpg",
      "sourceimg": "images/3-lg.png"
    }, {
      "name": "北京软柿子家居有限公司",
      "description": "一站式网上家居购物平台！",
      "thumbnail": "images/5.jpg",
      "sourceimg": "images/5-lg.jpg"
    }, {
      "name": "塔沟武校",
      "description": "全球最大的武学院校，在校师生4万余人，文武双修尽在塔沟！",
      "thumbnail": "images/1.jpg",
      "sourceimg": "images/1-lg.png"
    }, {
      "name": "鹿客智能锁",
      "description": "全国十大品牌，技术和理念双领先，智能家具领先者！",
      "thumbnail": "images/6.jpg",
      "sourceimg": "images/6-lg.png"
    }, {
      "name": "中国石油天然气管道局-",
      "description": "项目管控平台软件，让项目进展一目了然！",
      "thumbnail": "images/2.jpg",
      "sourceimg": "images/2-lg.jpg"
    }, {
      "name": "怀府姜糖膏",
      "description": "一站式微信直销平台，节省公司人力成本，快速铺货新渠道！",
      "thumbnail": "images/7.jpg",
      "sourceimg": "images/7-lg.jpg"
    }, {
      "name": "郑大三附院",
      "description": "（原河南省妇幼保健院）全省规模最大，最专业，技术最先进的公立妇幼医院，呵护母子/女平安从我们开始！",
      "thumbnail": "images/9.jpg",
      "sourceimg": "images/9-lg.jpg"
    }, {
      "name": " 河南希德利机械设备有限公司",
      "description": "饲料颗粒机、饲料粉碎机、铡草机，网站优化能上行业词才叫牛！",
      "thumbnail": "images/11.jpg",
      "sourceimg": "images/11-lg.jpg"
    }, {
      "name": "索菲亚酒店",
      "description": "拼车，酒店，饭店的预订微信小程序，一级横向分销模式，增加与顾客的粘性！",
      "thumbnail": "images/10.jpg",
      "sourceimg": "images/10-lg.jpg"
    }, {
      "name": "尚品良玉",
      "description": "尚品良玉",
      "thumbnail": "images/4.jpg",
      "sourceimg": "images/4-lg.png"
    }, {
      "name": "海南房地产联展中心",
      "description": "给您提供理想的房产项目，让您舒心安家！",
      "thumbnail": "images/8.jpg",
      "sourceimg": "images/8-lg.jpg"
    }, {
      "name": "信阳银行",
      "description": "您身边的金融理财专家！",
      "thumbnail": "images/12.jpg",
      "sourceimg": "images/12-lg.jpg"
    }]
  };
});
